/**
 * @fileoverview gRPC-Web generated client stub for myservice
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.12.4
// source: task_service.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.myservice = require('./task_service_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.myservice.TaskServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.myservice.TaskServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.myservice.TaskRequest,
 *   !proto.myservice.TaskResponse>}
 */
const methodDescriptor_TaskService_ProcessTask = new grpc.web.MethodDescriptor(
  '/myservice.TaskService/ProcessTask',
  grpc.web.MethodType.UNARY,
  proto.myservice.TaskRequest,
  proto.myservice.TaskResponse,
  /**
   * @param {!proto.myservice.TaskRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.myservice.TaskResponse.deserializeBinary
);


/**
 * @param {!proto.myservice.TaskRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.myservice.TaskResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.myservice.TaskResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.myservice.TaskServiceClient.prototype.processTask =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/myservice.TaskService/ProcessTask',
      request,
      metadata || {},
      methodDescriptor_TaskService_ProcessTask,
      callback);
};


/**
 * @param {!proto.myservice.TaskRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.myservice.TaskResponse>}
 *     Promise that resolves to the response
 */
proto.myservice.TaskServicePromiseClient.prototype.processTask =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/myservice.TaskService/ProcessTask',
      request,
      metadata || {},
      methodDescriptor_TaskService_ProcessTask);
};


module.exports = proto.myservice;

